config/routes.rb
Rails.application.routes.draw do
  root 'users#index'

  resources :users
  resources :pets

  resources :sessions, only: [:new, :create, :destroy]
  get "/auth/:provider/callback", to: "sessions#create"
  get "/signout", to: "sessions#destroy", as: :signout

end

app/models/pet.rb
class Pet < ActiveRecord::Base
	belongs_to :user
	has_one :pet_type
	after_initialize :init

	def init
		self.hunger ||= 0
	end

	def grow_hungry
		self.hunger += 1 unless self.hunger == 3
		self.assign_image
	end

	def feed
		self.hunger -= 1 unless self.hunger == 0
		self.assign_image
	end

	def assign_image
		animal = self.pet_type_id
		case self.hunger
		when 3
			image = PetType.find(animal).photo_url_1
		when 2
			image = PetType.find(animal).photo_url_2
		when 1
			image = PetType.find(animal).photo_url_3
		when 0
			image = PetType.find(animal).photo_url_4
		end
		self.update(image: image)
	end

end

app/models/pet_type.rb
class PetType < ActiveRecord::Base
	belongs_to :pet
end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
	belongs_to :user

	def self.get_tweets(user)
	  consumer_key = OAuth::Consumer.new(Rails.application.secrets.twitter_consumer_key, Rails.application.secrets.consumer_secret)
	  oauth_token = OAuth::Token.new(Rails.application.secrets.twitter_access_token, Rails.application.secrets.oauth_token_secret)

	  baseurl = "https://api.twitter.com/"
		sn = user
		path = "1.1/statuses/user_timeline.json?screen_name=#{sn}&count=1"
		address = URI("#{baseurl}#{path}")

		http = Net::HTTP.new address.host, address.port
    http.use_ssl = true
    http.verify_mode = OpenSSL::SSL::VERIFY_PEER
    
    request = Net::HTTP::Get.new address.request_uri
    request.oauth! http, consumer_key, oauth_token
    http.start
    response = http.request(request)

    JSON.parse(response.body)
	end
end

app/models/user.rb
class User < ActiveRecord::Base
	has_one :pet, dependent: :destroy
	has_many :tweets

	def self.create_with_omniauth(auth)
	  create! do |user|
	    user.provider = auth["provider"]
	    user.uid = auth["uid"]
	    user.name = auth["info"]["name"]
	    user.screen_name = auth["info"]["nickname"]
	  end
	end

	def tweets
		tweet = Tweet.get_tweets(self.screen_name)
	end

	def User.new_remember_token
		SecureRandom.urlsafe_base64
	end

	def User.hash(token)
		Digest::SHA1.hexdigest(token.to_s)
	end

	private

	def create_remember_token
		remember_token = User.hash(User.new_remember_token)
	end

	def normalize_fields
		self.email.downcase!
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

	private

	def current_user
	  @current_user ||= User.find(session[:user_id]) if session[:user_id]
	end
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController

	def index
		@pets = Pet.all
	end

	def show
		@pet = Pet.find( params[:id] )
		@first_name = current_user.name.split(" ")[0]
	end

	def new
		@pet = Pet.new
		@types = PetType.all
	end

	def create
		@pet = Pet.new(pet_params.merge(user_id: current_user.id))
		@pet.assign_image
		if @pet.save
			redirect_to @pet
		end
	end

	def edit
		@pet = Pet.find( params[:id] )
	end

	def update
		@pet = Pet.find( params[:id] )
		
		if @pet.update(pet_params)
			redirect_to @pet
		end
	end

	def destroy
		@pet = Pet.find( params[:id] )
		@pet.destroy
		redirect_to pets_url
	end

	private

	def pet_params
		params.require(:pet).permit(:name, :pet_type_id)
	end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	
	def new
	end

	def create
	  auth = request.env["omniauth.auth"]
	  user = User.find_by_provider_and_uid(auth["provider"], auth["uid"]) || User.create_with_omniauth(auth)
	  session[:user_id] = user.id
	  redirect_to root_url, notice: "Signed in!"
	end

	def destroy
	  session[:user_id] = nil
	  redirect_to root_url, notice: "Signed out!"
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def index
		@pet = Pet.find_by(user: current_user)
	end

	def show
		@user = User.find( params[:id] )
	end

	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		if @user.save
			redirect_to @user
		end
	end

	def edit
		@user = User.find( params[:id] )
	end

	def update
		@user = User.find( params[:id] )
		if user.update(user_params)
			redirect_to @user
		end
	end

	def destroy
		@user = User.find( params[:id] )
		@user.destroy
		redirect_to users_url
	end

	private

	def user_params
		params.require(:user).permit(:name, :email)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tweetagotchi</title>
  <link href='http://fonts.googleapis.com/css?family=Press+Start+2P' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<h1>Tweetagotchi</h1>

<div id='login_nav'>
	<% if current_user %>
	  Welcome <%= current_user.name %>!
	  <%= link_to "Sign Out", signout_path %>
	<% else %>
	  <%= link_to "Sign in with Twitter", "/auth/twitter" %>
	<% end %>
<div> <!-- end login_nav -->

<%= yield %>

</body>
</html>

app/views/pets/_form.html.erb
<%= form_for(@pet) do |f| %>
	Name: <%= f.text_field :name %><br>
	Species: 
	<% @types.each do |species| %>
		<%= f.radio_button :pet_type_id, species.id %>
		<%= f.label :pet_type_id, species.animal.capitalize %>
	<% end %>
	<br><%= f.submit %>
<% end %>

app/views/pets/index.html.erb
<h2>Your Pet:</h2>

<%= image_tag(@pets.first.image, class: "style_image") %>

app/views/pets/new.html.erb
<h2>Create your new pet:</h2>

<%= render 'form' %>

app/views/pets/show.html.erb
<h2>Hi, <%= current_user.name %> this is your pet!</h2>

<%#= image_tag(@pet.image, class: "style_image") %>

<img src=<%= @pet.image %> />
<h2><%= @pet.name %></h2>

app/views/users/idex.html.erb
idex.html.erb

app/views/users/index.html.erb
<% if current_user && @pet %>
	<%= image_tag @pet.image %>
	<h2><%= @pet.name %></h2>
<% elsif current_user %>
	<h2><%= link_to "Create Pet", new_pet_path %></h2>
<% end %>